# Generated by Django 4.0.1 on 2022-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_movieinfo_alter_userinfo_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('movie_name', models.CharField(max_length=16, verbose_name='电影名')),
                ('viewer_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('star', models.CharField(max_length=2, verbose_name='评星')),
                ('comment_time', models.DateTimeField(verbose_name='评论时间')),
                ('comment', models.TextField(verbose_name='电影评论')),
            ],
        ),
    ]
