# Generated by Django 4.0.1 on 2022-04-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_movie_remove_comments_movie_name_comments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.movie', verbose_name='电影名'),
        ),
    ]
