# Generated by Django 4.0.1 on 2022-04-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_prettynum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
