# Generated by Django 4.0.1 on 2022-04-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.CharField(max_length=128, verbose_name='影片名'),
        ),
    ]
