# Generated by Django 4.0.1 on 2022-04-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_alter_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='排名'),
        ),
    ]
