# Generated by Django 4.0.1 on 2022-04-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_alter_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
