# Generated by Django 4.0.1 on 2022-04-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_alter_comments_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('problem', models.TextField(verbose_name='问题描述')),
                ('img', models.FileField(upload_to='problem/', verbose_name='问题截图')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.userinfo', verbose_name='用户id')),
            ],
        ),
    ]
