# Generated by Django 4.0.1 on 2022-04-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boss',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='order',
            name='admin',
        ),
        migrations.DeleteModel(
            name='PrettyNum',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
